### ISSUE TITLE
Generating getters only.

### ISSUE THREAD

**Issue by WouterSioen** [adoy/vim-php-refactoring-toolbox#18]
Would it be possible to add a method to only add getters? I use the constructor instead of setters most of the time to preserve encapsulation and it would help me if I shouldn't have to remove the setters all the time.

**Comment by ilkermutlu** [comment]
@adoy I could get this done by using the existing ```PhpCreateSettersAndGetters()``` method and extracting the getter part.

We could assign it to, let's say <Leader>cog as in "Create only getters".

Just asking this before creating a PR because you might have a more elegant solution in mind. I'm new to Vimscript so my solution involves a bit repetition.

Just assign it to me if it sounds OK.

**Comment by adoy** [comment]
Sounds good to me :-)
